### ISSUE TITLE
Compare to CSP (i.e. golang)

### ISSUE THREAD

**Issue by ralph-tice** [hseeberger/blog#1]
Thanks for the blog post!  Here are some thoughts I had which I was confused about, which may warrant a followup post by either of us.  I'll try to find time to work on this, since I am getting interested in picking Scala back up.

Communicating Sequential Processes seems to be competing with the Actor model in Akka.  I don't know enough about both to validate whether that's true or not.  I also need to research whether green threads are the same as goroutines...

One problem I have with Akka's implementation last time I looked at it is the default is unbounded queues for the mailboxes, which prevents optimization and is an unending source of problems at scale.  Maybe it is easier to map Actors into a serverless deployment rather than containers...

**Comment by hseeberger** [comment]
Thanks for sharing your thoughts. Actually I'm planing to add Disqus support to my blog. I don't think GitHub issues in this repo are a good place for discussions. Hence I will disable them. Sorry for any inconveniences.
